version: '3.8'
services:
  viberAdapter:
    build: 
      context: ./ViberAdapter/ViberAdapter/
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    networks:
      - chat-bots
networks:
  chat-bots:
    name: chat-bots
    external: true
    
